### ISSUE TITLE
The `set-output` command is deprecated

### ISSUE THREAD

**Issue by arg** [AkhileshNS/heroku-deploy#156]
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
We see this warning after deploy completes. As per the linked page:

> Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error

**Comment by clickclickonsal** [comment]
Hey @AkhileshNS, great github action you've built! I've noticed the same deprecations warnings, looks like @arg put a PR to fix! Would love to get this merged a fix for this soon so we can continue using this before this causes any deployment issues in the future. 🙇🏼

**Comment by Romack** [comment]
Hey @AkhileshNS , I believe the only thing you need to do is update to actions/core >= 1.10.0 .  They have updated the implemenation of `setOutput` in that version to be compliant.

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/#patching-your-actions-and-workflows

**Comment by AkhileshNS** [comment]
It's done. My apologies for letting this drag on for so long and thank you all for identifying this early on
