### ISSUE TITLE
Node Update

### ISSUE THREAD

**Issue by kubilay-guran-crea** [AkhileshNS/heroku-deploy#172]
We're encountering errors in our GitHub Actions because certain packages no longer support Node.js version 16:

`The engine "node" is incompatible with this module. Expected version ">=18". Got "16.20.2".
`
Could you please consider updating the Node.js version to a later LTS version? This update will help resolve the compatibility issues caused by package changes

**Comment by AkhileshNS** [comment]
Updated Node version to 18 in the latest release `v3.13.14`
