### ISSUE TITLE
Ubuntu-24 no longer includes the Heroku CLI as part of the runner image

### ISSUE THREAD

**Issue by qbunt** [AkhileshNS/heroku-deploy#182]
Either the documentation in this repo needs updating for the version released 2 days ago, or the install should be packed into this action. [Full list of packages here](https://github.com/actions/runner-images/issues/10636)

**Comment by AkhileshNS** [comment]
Thanks for raising, I've updated the documentation.

**Comment by qbunt** [comment]
@AkhileshNS Thanks for the fast response, was super surprising to see they had dropped so much out of the runner images for 24
