### ISSUE TITLE
Support for a fixed retry period or interval for health checks

### ISSUE THREAD

**Issue by kenchan0130** [AkhileshNS/heroku-deploy#23]
In some cases, when a health check is performed, Heroku is not yet up and running on the server.
So, a workflow will see it as a failure.

---

In my case

workflow: https://github.com/kenchan0130/twitter-like-feed/blob/f7808c2c1c73793d65867f4f90dd789173503ace/.github/workflows/ci.yml#L56-L63
build: https://github.com/kenchan0130/twitter-like-feed/runs/885371417

**Comment by AkhileshNS** [comment]
I'll try setting up an option to manually configure a wait period before the healthcheck is to be performed. Hopefully that should fix your problem

**Comment by AkhileshNS** [comment]
I've added the option to manually configure a delay (in seconds) before performing healthcheck. Check the updated healthcheck documentation of the action for more info,

Let me know if this solves your problem and if it does, please close the issue

**Comment by kenchan0130** [comment]
@AkhileshNS 
Thank you for your support.

I changed my project config as https://github.com/kenchan0130/twitter-like-feed/commit/12ac5fd8cb40c25da404dbc8bf02fc4f34e5f9f7.

So far it looks fine.
If I have some problems, I will reopen this.
