### ISSUE TITLE
Why do we need the email?

### ISSUE THREAD

**Issue by rohitkrishna094** [AkhileshNS/heroku-deploy#29]
Why do we need the email? isn't api token enough? What is email being used for? I feel like its sensitive information to share in yml file.

**Comment by AkhileshNS** [comment]
The email requirement comes from Heroku itself. You can get information regarding this at ![https://devcenter.heroku.com/articles/authentication#usage-examples](https://devcenter.heroku.com/articles/authentication#usage-examples)

By default Heroku seems to require both the email as well as the API Key to login. If you're worried about privacy, then alternatively you can store the email in GitHub Secrets and reference it within your action.

**Comment by rohitkrishna094** [comment]
Thanks that's a great suggestion. Closing this now.
