### ISSUE TITLE
Support for pushing branches?

### ISSUE THREAD

**Issue by wootwoot1234** [AkhileshNS/heroku-deploy#3]
Thanks for this action, it's been very useful.

Is there any way to push a different branch to heroku?  I know when I'm pushing a branch to heroku from my local computer I use `git push HEROKU_APP_NAME BRANCH:master`.  Would it be possible to support different branches via maybe a `with` variable?

**Comment by AkhileshNS** [comment]
It should be possible. I'm currently busy but I'll see if I can add the feature by this evening. If you need it immediately, then you can try forking the repo and adding the feature itself.

You would just need to add
```
...
inputs:
  branch:
    default: "master"
...
```
in the action.yml file

And then in the index.js file use 
```javascript 
const branch = core.getInput("branch")
``` 
to get the value in code and replace 
```javascript 
execSync("git push heroku HEAD:refs/heads/master")
```
With
```javascript 
execSync("git push heroku HEAD:refs/heads/" + branch)
```

And you should technically be good to go. Again I'll try and officially add it to the repo by this evening.

P.S: Typed this comment out on my phone. Love the new Github Mobile App

**Comment by AkhileshNS** [comment]
I think I've managed to implement what you're looking for in the new release. Check out the documentation and hopefully you should find what you are looking for

**Comment by wootwoot1234** [comment]
Very cool, thank you!

I'm testing it now.  I'll let you know how it goes.

**Comment by AkhileshNS** [comment]
I'm going to assume that fixed your issue and on that note, closing this issue due to lack of inactivity

**Comment by wootwoot1234** [comment]
Yes, sorry for not closing it.  Works perfect, thanks again!
