### ISSUE TITLE
How to deploy an artifacts directory?

### ISSUE THREAD

**Issue by vighnesh153** [AkhileshNS/heroku-deploy#36]
I have a repository which has both the `client` and `server` directory. On push to master, I have a Github Action that compiles the client code and pastes its artifacts in the `server/dist` directory. 

When I try to deploy the `server` directory by setting the `appdir` value to `server`, it does deploy the server but the `dist` folder inside it is missing. How do I make sure that directories created in the github workflow are preserved?

**Comment by AkhileshNS** [comment]
Hey @vighnesh153, really sorry for replying so late. Regarding your issue, deployments to Heroku are generally done via git, so if you make changes to your application directory (even inside github actions), you will need to commit them before you can deploy them. 

A simple solution to your problem would be to add the following step just before the heroku deploy action

```yaml
- run: git config user.email "USER EMAIL" && git config user.name "USER NAME" && git add -A && git commit -m "Added artifacts"
```

Note. This seems to be a pretty common issue so I'm considering adding some a feature for this within the heroku deploy action itself so once that comes you won't have to worry about something like this (assuming that this is infact the issue)

**Comment by vighnesh153** [comment]
This makes sense. Thanks for updating.
