### ISSUE TITLE
Silent failure?

### ISSUE THREAD

**Issue by MaxHalford** [AkhileshNS/heroku-deploy#44]
Hello there! First of all, kudos because this is a great piece of software.

I've used it succesfully to deploy a Streamlit soundboard which you can find [here](https://chime-soundboard.herokuapp.com/). My problem is that Heroku app doesn't seem to be deployed anymore. You can my latest build trace [here](https://github.com/MaxHalford/chime/runs/1402742658?check_suite_focus=true). Here is the associated [workflow](https://github.com/MaxHalford/chime/blob/main/.github/workflows/soundboard.yml) as well as the [app directory](https://github.com/MaxHalford/chime/tree/main/soundboard).

Any clues?

**Comment by AkhileshNS** [comment]
Hey @MaxHalford, sorry for the late reply and I couldn't quite follow what your issue was. Would you mind explaining again with some specifics so I can help you out

**Comment by MaxHalford** [comment]
I've manage to fix the issue out of nowhere, not too sure what happened. It's highly likely I did something wrong. Sorry for the noise!

**Comment by AkhileshNS** [comment]
👍
