### ISSUE TITLE
Gh action step indicates success despite heroku release phase command failed

### ISSUE THREAD

**Issue by bfoese** [AkhileshNS/heroku-deploy#51]
Hey, first of all, thank you very much for this well documented action.
I setup a GitHub workflow with "heroku-deploy@v3.7.8". That worked fine. Now I extended my Procfile with a release command for database migration and noticed that the GitHub workflow indicates success even though the release command failed.

Is it possible to adapt the heroku-deploy action in a way that it reflects the failed release phase? 

One example of a failed release:
Step indicates success but should indicate failure instead:
![image](https://user-images.githubusercontent.com/1623552/103350178-68985000-4a9f-11eb-8c46-57230d3a224c.png)

Extract from the GitHub Action log of this step:
![image](https://user-images.githubusercontent.com/1623552/103351037-30464100-4aa2-11eb-881d-4a0be84ea9db.png)
![image](https://user-images.githubusercontent.com/1623552/103351113-756a7300-4aa2-11eb-95a5-cff4a07b92b8.png)

Heroku CLI status:
![image](https://user-images.githubusercontent.com/1623552/103350528-903be800-4aa0-11eb-9f06-273046ff9e62.png)

Step definition:
![image](https://user-images.githubusercontent.com/1623552/103351539-dc3c5c00-4aa3-11eb-9c5a-444436fe8b9d.png)

**Comment by AkhileshNS** [comment]
Hey @bfoese, the App's logging definitely needs some improving and I am working on this as of the moment. I should have some improvements in a few days, I'll keep you updated

**Comment by AkhileshNS** [comment]
In the meantime, you could try using the healthcheck option to create a url which checks if the release phase has been executed properly

**Comment by AkhileshNS** [comment]
Closing this action due to inactivity. Please reopen it if this issue is still relevant to you

**Comment by jasonbouffard** [comment]
This is a good issue. We experienced the same recently. Migration failed, Heroku release failed, GH action succeeded. Wondering if a fix was ever implemented or an available config to blowup on release failure?

**Comment by jasonbouffard** [comment]
This step after a `akhileshns/heroku-deploy` step should catch failures.

```
      - name: Validate Heroku Release
        run: |
          release_status=$(heroku releases --json --num=1 --app ${{ vars.HEROKU_APP_NAME }} | jq -r '.[0].status')
          if [ "$release_status" != "succeeded" ]; then
            echo "Heroku release failed"
            exit 1
          fi
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
```
