### ISSUE TITLE
Need more build detail

### ISSUE THREAD

**Issue by qiwang97** [AkhileshNS/heroku-deploy#53]
I set `usedocker: true` in my action. But it runs slow when build with docker without stdout.
Is there anyway to show more build details when use with docker?

**Comment by AkhileshNS** [comment]
Hey @qiwang97, GitHub Actions by default does print the logs of whatever commands are used in an action. The only thing that could be done to maybe improve logging is add console.logs to the outputs of the execSync functions in the action. Essentially wherever you see:-

```javascript
execSync('something');
```

you would replace that with

```javascript
console.log(execSync('something'))
```

Though I don't know how much that would help and it might even make up your logs. Regardless I would encourage you to fork the repo and make that change, or I can also make a branch with this variant that you can try if you want.

On a side node. It is also a little strange that the build runs slower when the output from docker isn't printed out, I would assume it should run faster in that case.

**Comment by qiwang97** [comment]
Thanks and i will try. I just want to see which step is slow and find the reason.

**Comment by AkhileshNS** [comment]
Closing this action due to inactivity. Please reopen it if this issue is still relevant to you
