### ISSUE TITLE
Multiple rollbacks when using the checkstring option?

### ISSUE THREAD

**Issue by Kaltsoon** [AkhileshNS/heroku-deploy#70]
I noticed that for some reason two rollbacks occur when using the `checkstring` option. After looking at [the specific part](https://github.com/AkhileshNS/heroku-deploy/blob/50f29c7a8bc4d643a53b35a0303a1b9b5fcaf12f/index.js#L240) of source code I found out that there are actually two calls for the `healthcheckFailed` function in this case: one for the invalid status code and one for the invalid `checkstring`. Is this intentional?

**Comment by AkhileshNS** [comment]
Hey @Kaltsoon. No the healthcheckfailed function really shouldn't be setup that way. Thanks for pointing that out. I'll have a fix ready at the earliest

**Comment by AkhileshNS** [comment]
Hey @Kaltsoon, I've updated the latest version of the app to avoid performing a rollback twice. Please have a look and let me know if this fixes your problem. If it does, then please close the issue.

**Comment by Kaltsoon** [comment]
It works, thanks!
