### ISSUE TITLE
Added a new dependency, now wont deploy

### ISSUE THREAD

**Issue by kieron** [AkhileshNS/heroku-deploy#71]
Hi, this was working great for me, but now I am seeing an issue since adding this dependency: https://www.npmjs.com/package/@vue-hero-icons/outline

Here is the output:

```
remote: -----> Installing dependencies        
remote:        Installing node modules        
remote:        npm ERR! Error while executing:        
remote:        npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/tailwindlabs/heroicons.git        
remote:        npm ERR!         
remote:        npm ERR! Host key verification failed.        
remote:        npm ERR! fatal: Could not read from remote repository.
remote:        npm ERR!         
remote:        npm ERR! Please make sure you have the correct access rights        
remote:        npm ERR! and the repository exists.
remote:        npm ERR!         
remote:        npm ERR! exited with error code: 128        
remote:                
remote:        npm ERR! A complete log of this run can be found in:        
remote:        npm ERR!     /tmp/npmcache.QSl5O/_logs/2021-02-22T11_44_18_252Z-debug.log        
remote: 
remote: -----> Build failed
```

I also see this

```remote: !	Push rejected to rubric-front-end.        
remote: 
To https://git.heroku.com/rubric-front-end.git
 ! [remote rejected] HEAD -> main (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/rubric-front-end.git'

            Unable to push branch because the branch is behind the deployed branch. Using --force to deploy branch. 
            (If you want to avoid this, set dontuseforce to 1 in with: of .github/workflows/action.yml. 
            Specifically, the error was: Error: Command failed: git push heroku HEAD:refs/heads/main
```

This build works perfectly locally, it is only when I push to deploy it does this. It was working great for ages :)

Thanks in advance for anyone who may know!

**Comment by AkhileshNS** [comment]
Hey @kieron, it seems strange that the deployment is failing because of a specific dependency in your project. Can you confirm if removing the dependency makes it deploy properly again?

**Comment by AkhileshNS** [comment]
Also make sure that you don't have both a yarn.lock and package-lock.json file (This happened to me once), If you have two lock files, it won't work, you'll need to remove one

**Comment by kieron** [comment]
> Hey @kieron, it seems strange that the deployment is failing because of a specific dependency in your project. Can you confirm if removing the dependency makes it deploy properly again?

Hey @AkhileshNS thanks for your response, you're totally right it is strange.

I actually had some luck at getting it to build on the remote by setting the engines for node & npn, in my package.json to be very strict & an exact match of what is on my machine.

I'd of probably tried something along those lines sooner but we all know how useful the npm error output is 😅

But to answer your question it was successful as soon as I removed that package, but I still don't know enough about why a node/npm mismatch would cause this. 

I think your in the clear though and it's all my fault 😁

**Comment by AkhileshNS** [comment]
Hey @kieron. Good to hear. If it's in the clear then I'll close the issue.
