### ISSUE TITLE
Deploy Even if Files Didn't Change

### ISSUE THREAD

**Issue by sillvva** [AkhileshNS/heroku-deploy#85]
I have a script that runs during the app build phase on Heroku to fetch files from Firebase Storage prior to building. So, I've setup a Firebase Function to dispatch a workflow to redeploy to Heroku whenever a file is created, updated, or deleted on Firebase Storage.

However, whenever the deploy step processes on Github Actions, it just says "Everything up-to-date" and doesn't trigger a build on Heroku. This is likely because there were no code changes, so the Github repo and Heroku repo are both up-to-date.

Is there a way to force the deploy to trigger a rebuild?

**Comment by sealabcore** [comment]
I saw this was closed, but how did you force the deploy even if no files have changed?
